[package]
name = "MinT"
version = "0.1.0"
edition = "2024"

[dependencies]
portable-pty = "0.9.0"
winit = "0.30.12"
wgpu = "26.0.1"
vte = "0.15.0"
cosmic-text = "0.14.2"
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0.98"
pollster = "0.4.0"
